#!/bin/bash

CMD=$1
shift

readarray -d ',' -t mapping <<< "$VOLUME_MAPPING"

args=("$@")
#echo "args: ${args[@]}"
for map in "${mapping[@]}"
do
        map="${map//[$'\t\r\n ']}"
        readarray -d '=' -t m <<< "$map"
        src="${m[0]//[$'\t\r\n ']}"
        tgt="${m[1]//[$'\t\r\n ']}"
#        echo "$src -> $tgt"
        args=("${args[@]/$src/$tgt}")
#        echo "args: ${args[@]}"
done
${CMD} "${args[@]}"
